name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls && pwd
      - name: Git commands
        run: |
          git status && git config --list
      - name: Current branch
        run: |
          git branch -q
      - name: OS infos
        run: |
          df -h && free -mh & lscpu
      - name: Geolocation
        run: |
          sudo apt-get install curl -y
          curl https://ipinfo.io/ip
